FROM node:14.21.2-alpine3.17 AS node_api
WORKDIR /usr/src/app
COPY . ./nodeapi/

RUN cd nodeapi && npm install

FROM node:14.21.2-alpine3.17

WORKDIR /usr/src/app


COPY --from=node_api /usr/src/app/nodeapi/ ./
RUN ls
EXPOSE 5000
CMD ["/bin/sh", "-c", "cd /usr/src/app/ && npm start"]
