apiVersion: v1
kind: Service
metadata:
  name: emart-service
  labels:
    app: emart-service
    auther: Tawfeeq
spec:
  selector:
    app: emart-app
  ports:
   - protocol: TCP
     port: 3306
  type: LoadBalancer
